In [1]:
%pylab inline
import pandas as pd
from sklearn.preprocessing import StandardScaler
df=pd.read_csv('/home/anu/Desktop/animdata.csv',sep='\t')
df
#pylab gives numpy's options


Populating the interactive namespace from numpy and matplotlib


Species    BodyWt  BrainWt  NonDreaming  Dreaming  \
0          Africanelephant  6654.000   5712.0          NaN       NaN   
1   Africangiantpouchedrat     1.000      6.6          6.3       2.0   
2                ArcticFox     3.385     44.5          NaN       NaN   
3     Arcticgroundsquirrel     0.920      5.7          NaN       NaN   
4            Asianelephant  2547.000   4603.0          2.1       1.8   
..                     ...       ...      ...          ...       ...   
57               Treehyrax     2.000     12.3          4.9       0.5   
58               Treeshrew     0.104      2.5         13.2       2.6   
59                  Vervet     4.190     58.0          9.7       0.6   
60            Wateropossum     3.500      3.9         12.8       6.6   
61    Yellow-belliedmarmot     4.050     17.0          NaN       NaN   

    TotalSleep  LifeSpan  Gestation  Predation  Exposure  Danger  
0          3.3      38.6      645.0          3         5       3  
1          8.3       4.5       42.0          3         1       3  
2         12.5      14.0       60.0          1         1       1  
3         16.5       NaN       25.0          5         2       3  
4          3.9      69.0      624.0          3         5       4  
..         ...       ...        ...        ...       ...     ...  
57         5.4       7.5      200.0          3         1       3  
58        15.8       2.3       46.0          3         2       2  
59        10.3      24.0      210.0          4         3       4  
60        19.4       3.0       14.0          2         1       1  
61         NaN      13.0       38.0          3         1       1  

[62 rows x 11 columns]

# #standardscaler standardizing the data between 0 & 1

In [2]:
df.head()
#first 5 rows

Species    BodyWt  BrainWt  NonDreaming  Dreaming  \
0         Africanelephant  6654.000   5712.0          NaN       NaN   
1  Africangiantpouchedrat     1.000      6.6          6.3       2.0   
2               ArcticFox     3.385     44.5          NaN       NaN   
3    Arcticgroundsquirrel     0.920      5.7          NaN       NaN   
4           Asianelephant  2547.000   4603.0          2.1       1.8   

   TotalSleep  LifeSpan  Gestation  Predation  Exposure  Danger  
0         3.3      38.6      645.0          3         5       3  
1         8.3       4.5       42.0          3         1       3  
2        12.5      14.0       60.0          1         1       1  
3        16.5       NaN       25.0          5         2       3  
4         3.9      69.0      624.0          3         5       4

In [3]:
df.tail()
#last 5 rows

Species  BodyWt  BrainWt  NonDreaming  Dreaming  TotalSleep  \
57             Treehyrax   2.000     12.3          4.9       0.5         5.4   
58             Treeshrew   0.104      2.5         13.2       2.6        15.8   
59                Vervet   4.190     58.0          9.7       0.6        10.3   
60          Wateropossum   3.500      3.9         12.8       6.6        19.4   
61  Yellow-belliedmarmot   4.050     17.0          NaN       NaN         NaN   

    LifeSpan  Gestation  Predation  Exposure  Danger  
57       7.5      200.0          3         1       3  
58       2.3       46.0          3         2       2  
59      24.0      210.0          4         3       4  
60       3.0       14.0          2         1       1  
61      13.0       38.0          3         1       1

In [4]:
df.isna().sum()
#NaN values count in each column

Species         0
BodyWt          0
BrainWt         0
NonDreaming    14
Dreaming       12
TotalSleep      4
LifeSpan        4
Gestation       4
Predation       0
Exposure        0
Danger          0
dtype: int64

# #shows some correlated values, ie,taking sqr & cube of 

In [5]:
df['squared']=df['BodyWt']**2
df['cubed']=df['BodyWt']**3
X=df[['BodyWt','squared','cubed']]
X

y=df[['BrainWt']]
y

BrainWt
0    5712.0
1       6.6
2      44.5
3       5.7
4    4603.0
..      ...
57     12.3
58      2.5
59     58.0
60      3.9
61     17.0

[62 rows x 1 columns]

# #standardscaler standardizing the data between 0 & 1

In [6]:
xscaled= StandardScaler().fit_transform(X)
yscaled= StandardScaler().fit_transform(y)
print(yscaled)
xscaled
#In output value, 1st is an outlayer ,
#reamining values are under standard normal distribution -1 (mid portion of that bell curve)

[[ 5.88337924]
 [-0.29968608]
 [-0.25861303]
 [-0.30066143]
 [ 4.68153196]
 [-0.11231062]
 [-0.30651353]
 [-0.12368969]
 [-0.27909537]
 [ 0.16999887]
 [-0.29990283]
 [ 0.1515756 ]
 [-0.30423771]
 [ 0.14724071]
 [-0.30553818]
 [-0.27974561]
 [-0.30304562]
 [-0.30142004]
 [-0.28787352]
 [-0.2190572 ]
 [ 0.43009205]
 [-0.18221066]
 [-0.30575492]
 [ 0.13315233]
 [ 0.04537088]
 [-0.17733391]
 [-0.30250376]
 [-0.30087818]
 [ 0.40299901]
 [-0.13669435]
 [-0.24615024]
 [-0.30668693]
 [-0.30656772]
 [ 1.12367389]
 [-0.30358748]
 [-0.2980605 ]
 [-0.30640516]
 [-0.30648102]
 [-0.3000112 ]
 [-0.29513445]
 [ 0.22418495]
 [-0.29004096]
 [-0.18221066]
 [-0.29448422]
 [-0.11176876]
 [-0.29372561]
 [-0.26435676]
 [-0.30477958]
 [-0.25221908]
 [-0.11285248]
 [-0.29350887]
 [-0.28408049]
 [-0.20041718]
 [-0.11718736]
 [-0.29329213]
 [-0.30575492]
 [-0.30402097]
 [-0.29350887]
 [-0.30412934]
 [-0.24398279]
 [-0.30261213]
 [-0.28841538]]


array([[ 7.23777846e+00,  7.72735550e+00,  7.79798404e+00],
       [-2.21768166e-01, -1.48525148e-01, -1.35321659e-01],
       [-2.19094031e-01, -1.48523288e-01, -1.35321658e-01],
       [-2.21857864e-01, -1.48525176e-01, -1.35321659e-01],
       [ 2.63288473e+00,  1.00543647e+00,  3.09609310e-01],
       [-2.11060414e-01, -1.48505528e-01, -1.35321627e-01],
       [-2.22863608e-01, -1.48525326e-01, -1.35321659e-01],
       [-4.34925137e-02, -1.43971531e-01, -1.35211361e-01],
       [-2.19189336e-01, -1.48523389e-01, -1.35321658e-01],
       [-1.64406013e-01, -1.48041367e-01, -1.35317837e-01],
       [-2.22412873e-01, -1.48525294e-01, -1.35321659e-01],
       [ 2.98482794e-01, -1.10062655e-01, -1.32614182e-01],
       [-2.22272720e-01, -1.48525272e-01, -1.35321659e-01],
       [-1.31071667e-02, -1.42298294e-01, -1.35145288e-01],
       [-2.22805304e-01, -1.48525325e-01, -1.35321659e-01],
       [-2.19525705e-01, -1.48523725e-01, -1.35321658e-01],
       [-2.22009230e-01, -1.48525217e-01

In [7]:
#Based on position ,it gives -ve and +ve values 
# 3 coulumns indicate bodywt,squared and cubed values

In [14]:
from sklearn.model_selection import train_test_split,GridSearchCV,KFold
from sklearn.linear_model import Lasso,Ridge

#splitting the data into 80:20 %
xtrain,xtest,ytrain,ytest=train_test_split(xscaled,yscaled,test_size=0.2,random_state=42)

#a range of values generating and finding lambda value
lambda_range = linspace(0.001,0.2,25)
lambda_range

ridge_model = Ridge(max_iter=10000)
lasso_model = Lasso(max_iter=10000)

#this must be in list or dictionary format,and here "alpha" is the name of lambda variable 
lambda_grid=[{'alpha':lambda_range}]

#splitting train data into 20 folds here for both lasso and ridge and cross validating

cv_ridge =GridSearchCV(estimator=ridge_model,param_grid=lambda_grid,cv=KFold(n_splits=20))
cv_lasso =GridSearchCV(estimator=lasso_model,param_grid=lambda_grid,cv=KFold(n_splits=20))

cv_ridge.fit(xtrain,ytrain)
cv_lasso.fit(xtrain,ytrain)

GridSearchCV(cv=KFold(n_splits=20, random_state=None, shuffle=False),
             estimator=Lasso(max_iter=10000),
             param_grid=[{'alpha': array([0.001     , 0.00929167, 0.01758333, 0.025875  , 0.03416667,
       0.04245833, 0.05075   , 0.05904167, 0.06733333, 0.075625  ,
       0.08391667, 0.09220833, 0.1005    , 0.10879167, 0.11708333,
       0.125375  , 0.13366667, 0.14195833, 0.15025   , 0.15854167,
       0.16683333, 0.175125  , 0.18341667, 0.19170833, 0.2       ])}])

In [15]:
#Above values are generated from 10,000 iteration and from that range of values,
#lambda value will be tuned for ridge & lasso from that array set

ridge_lambda = cv_ridge.best_params_['alpha']
lasso_lambda = cv_lasso.best_params_['alpha']
print(ridge_lambda)
print(lasso_lambda)

0.2
0.009291666666666667


## we got lambda values 1 and 2 here ,now finding intercept/coef  for lasso and ridge using lambda values

In [17]:
brain_lasso = Lasso(alpha=lasso_lambda,max_iter=10000)
brain_ridge = Ridge(alpha=ridge_lambda,max_iter=10000)

brain_lasso.fit(xtrain,ytrain)
brain_ridge.fit(xtrain,ytrain)

lasso_predict = brain_lasso.predict(xtest)
ridge_predict = brain_ridge.predict(xtest)
print(brain_lasso.coef_)
print(brain_ridge.coef_)
print()
print("residual/meansquared error for lasso: %.4f"%np.mean(lasso_predict-ytest)**2)
print("residual/meansquared error for ridge: %.4f"%np.mean(ridge_predict-ytest)**2)

#Here below,since lasso having unwanted values/coeff includes 0,0 its residual is not good,
#only first value of lass will be considered
#For ridge, residual values got shrinked(reduced) and goes approximately close to 0[last 2 values]

[1.62103433 0.         0.        ]
[[1.30085389 0.79149775 0.33979014]]

residual/meansquared error for lasso: 0.1874
residual/meansquared error for ridge: 0.8982


In [18]:
from sklearn.metrics import r2_score
r2_score(lasso_predict,ytest)

#score of lasso is good when compared to ridge

0.736615958477502

In [19]:
from sklearn.metrics import r2_score
r2_score(ridge_predict,ytest)

#score of ridge is very less since it got the effect of the squared and cubed value of bodywt

0.5114010421678362